### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by jnormile** [term-world/term-hub#63]
Ran into an issue where attempting to open a Markdown preview resulted in the following error prompt appearing:

```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

Apache/2.4.53 (Ubuntu) Server at cdr.theterm.world Port 443
```

However, this was while I was still able to use the rest of the VS Code browser as expected.

**Comment by dluman** [comment]
This appears to be fixed by #77 -- it was a websocket issue.
